/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type AddRoleDTORole = typeof AddRoleDTORole[keyof typeof AddRoleDTORole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddRoleDTORole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  ASHA: 'ASHA',
} as const;
