/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface ApiResponse {
  timestamp?: string;
  success?: boolean;
  status?: number;
  message?: string;
  payload?: unknown;
}
