/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { UserDTO } from './userDTO';

export interface ApiResponseUserDTO {
  timestamp?: string;
  success?: boolean;
  status?: number;
  message?: string;
  payload?: UserDTO;
}
