/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokenResponse } from './authTokenResponse';

export interface ApiResponseAuthTokenResponse {
  timestamp?: string;
  success?: boolean;
  status?: number;
  message?: string;
  payload: AuthTokenResponse;
}
