/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { JwtUser } from './jwtUser';

export interface AuthTokenResponse {
  user?: JwtUser;
  accessToken?: string;
  tokenType?: string;
  expiresIn?: number;
  exp?: string;
}
