/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface ContentDisposition {
  type?: string;
  name?: string;
  filename?: string;
  charset?: string;
  /** @deprecated */
  size?: number;
  /** @deprecated */
  creationDate?: string;
  /** @deprecated */
  modificationDate?: string;
  /** @deprecated */
  readDate?: string;
  attachment?: boolean;
  formData?: boolean;
  inline?: boolean;
}
