/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponseHeadersHostAddress } from './errorResponseHeadersHostAddress';

export type ErrorResponseHeadersHost = {
  hostString?: string;
  address?: ErrorResponseHeadersHostAddress;
  port?: number;
  unresolved?: boolean;
  hostName?: string;
};
