/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { HttpMethod } from './httpMethod';
import type { ErrorResponseHeadersHost } from './errorResponseHeadersHost';
import type { MediaType } from './mediaType';
import type { ErrorResponseHeadersAcceptLanguageItem } from './errorResponseHeadersAcceptLanguageItem';
import type { ContentDisposition } from './contentDisposition';
import type { HttpRange } from './httpRange';
import type { ErrorResponseHeadersAll } from './errorResponseHeadersAll';

export type ErrorResponseHeaders = {
  location?: string;
  allow?: HttpMethod[];
  host?: ErrorResponseHeadersHost;
  cacheControl?: string;
  contentLanguage?: string;
  etag?: string;
  accept?: MediaType[];
  accessControlAllowOrigin?: string;
  accessControlAllowMethods?: HttpMethod[];
  accessControlAllowHeaders?: string[];
  accessControlExposeHeaders?: string[];
  accessControlAllowCredentials?: boolean;
  accessControlMaxAge?: number;
  accessControlRequestMethod?: HttpMethod;
  accessControlRequestHeaders?: string[];
  acceptPatch?: MediaType[];
  basicAuth?: string;
  acceptLanguage?: ErrorResponseHeadersAcceptLanguageItem[];
  acceptLanguageAsLocales?: string[];
  acceptCharset?: string[];
  bearerAuth?: string;
  connection?: string[];
  contentDisposition?: ContentDisposition;
  expires?: number;
  ifMatch?: string[];
  ifNoneMatch?: string[];
  ifUnmodifiedSince?: number;
  origin?: string;
  pragma?: string;
  range?: HttpRange[];
  upgrade?: string;
  vary?: string[];
  ifModifiedSince?: number;
  contentType?: MediaType;
  contentLength?: number;
  empty?: boolean;
  all?: ErrorResponseHeadersAll;
  lastModified?: number;
  date?: number;
  [key: string]: string[];
};
