/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { ProblemDetail } from './problemDetail';
import type { ErrorResponseStatusCode } from './errorResponseStatusCode';
import type { ErrorResponseHeaders } from './errorResponseHeaders';

export interface ErrorResponse {
  detailMessageArguments?: unknown[];
  typeMessageCode?: string;
  detailMessageCode?: string;
  titleMessageCode?: string;
  body?: ProblemDetail;
  statusCode?: ErrorResponseStatusCode;
  headers?: ErrorResponseHeaders;
}
