/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { JwtUserRolesItem } from './jwtUserRolesItem';
import type { JwtUserStatus } from './jwtUserStatus';

export interface JwtUser {
  id?: string;
  username?: string;
  roles?: JwtUserRolesItem[];
  status?: JwtUserStatus;
}
