/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type JwtUserStatus = typeof JwtUserStatus[keyof typeof JwtUserStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JwtUserStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED',
} as const;
