/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA AUTH-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface RegistrationRequest {
  /**
   * @minLength 0
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 100
   */
  password: string;
}
